### ISSUE TITLE
Allowance for bindmounts and nativemounts default_opts

### ISSUE THREAD

**Issue by andylytical** [ncsa/puppet-spectrumscale#17]
Reduces redundancy for all mounts that use the same mount options.

Example:
```
gpfs::nativemounts::default_opts: noauto,nosuid,ro
gpfs::nativemounts::mountmap:
    fs0: {}
    fs1: {}
    fs2: {}
    fs3:
        opts: rw,suid
```
